name: Python Application CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
        
      - name: List directory structure
        run: find . -type d -print | sort

      - name: Install dependencies and package
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Uninstall the package if it's already installed. The "|| true" ensures the step doesn't fail if the package isn't installed.
          pip uninstall -y myapp || true
          pip install -e .
      
      - name: Run tests with pytest
        run: pytest --maxfail=1 --disable-warnings -q
